sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $281781b146117d930f169942a6e2e27c7a2398cc
  on:
    branch: master
