ROS_VISION_NODE_NAME = 'vision'
ROS_BRIDGE_ENCODING = "bgr8"

ROS_SUBSCRIBER_WEBCAM_TOPIC_NAME = "/usb_cam/image_raw"

ROS_PUBLISHER_VIDEO_FEED_TOPIC_NAME = "/usb_cam/image_ouput"
ROS_PUBLISHER_PUCK_POSITION_TOPIC_NAME = "/puck_pos"